config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/donate', path: :donate
  get 'static_pages/settings', path: :settings

  get 'static_pages/home', path: :home

  get 'search' => 'application#search', as: :search

   root 'static_pages#home'

  resources :climbers
  resources :posts
  resources :gears
  resources :gear_types
  resources :loans
  resources :events do
    member do
      get 'signup'
      get 'signdown'
    end
  end

  resources :app_configs, only: [:update]
  get '/app_configs' => 'app_configs#edit', as: :edit_app_configs
  resources :pending_climbers, only: [:new, :create, :index, :destroy]
  resources :faqs, except: [:show]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'front_page', only: :home

  def donate
  end

  def settings
    authorize! :manage, :settings
  end

  def home
    @events = Event.all.sample(5)
    @posts = Post.order('created_at DESC').limit(4)
    @faqs = Faq.all
  end
end

app/views/static_pages/_slide.html.slim
= content_tag :div, class: "slide", style: "background-image: url('#{slide.cover(:splash)}')"
  .heading_container.hidden-fade
    a href = event_path(slide)
      h3.slide_heading
         = slide.name
      h3.slide_subheading
        p
          = truncate slide.description, 64
  .slide-overlay
    a href = event_path(slide)

app/views/static_pages/contact.html.slim
h1
  | StaticPages#contact
p
  | Find me in app/views/static_pages/contact.html.erb

app/views/static_pages/donate.html.slim
#header_container
  h2
    | Support YCT
#content

app/views/static_pages/home.html.slim
#overlay
  #logo-container
    = embedded_svg('logo.svg',class: 'logo');



#slides
  - count = 0
  - @events.each do |e|
    = render partial: 'slide', locals: {index: count, slide: e}
    - count += 1

#wrapper.splash
  .about_wrapper
    .about_content
      = markdown @appconfig.about

  br
  .page
    .splash_title
      = link_to 'Recent News', posts_path
    = render partial: 'posts/post_card', collection: @posts
    .splash_title#faq
      | FAQ
    = render partial: 'faqs/faq_card', collection: @faqs
    p
      This site is powered by Ruby on Rails and dotdotdot.js. To report a bug, comment, or contribute, check out the <a href="https://github.com/squidgetx/yct">github</a>

app/views/static_pages/settings.html.slim
#header_container
  h2
    | Admin Panel

#content
  = link_to 'Manage Front Page FAQs', faqs_path, class: 'btn'
  = link_to 'Invite new users', new_pending_climber_path, class: 'btn'
  = link_to 'Manually add new users', new_climber_path, class: 'btn'
  = link_to 'Manage pending user invitations', pending_climbers_path, class: 'btn'
  = link_to 'Manage application settings', edit_app_configs_path, class: 'btn'
  = link_to 'Manage gear types', gear_types_path, class: 'btn'