config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/donate', path: :donate
  get 'static_pages/settings', path: :settings

  get 'static_pages/home', path: :home

  get 'search' => 'application#search', as: :search

   root 'static_pages#home'

  resources :climbers
  resources :posts
  resources :gears
  resources :gear_types
  resources :loans
  resources :events do
    member do
      get 'signup'
      get 'signdown'
    end
  end

  resources :app_configs, only: [:update]
  get '/app_configs' => 'app_configs#edit', as: :edit_app_configs
  resources :pending_climbers, only: [:new, :create, :index, :destroy]
  resources :faqs, except: [:show]

end

app/controllers/gear_types_controller.rb
class GearTypesController < ApplicationController
  
  before_action :find_gear_type, only: [:edit, :destroy, :update]

  def index
    @gear_types = GearType.all
    @new = new_gear_type_path(@gear_type)
  end

  def new
    @gear_type = GearType.new
  end

  def create
    p = gear_type_params
    @gear_type ||= GearType.new(p)
    if @gear_type.save
      redirect_to(gear_types_path, notice: 'Gear Type successfully updated')
    else
      render :new
    end
  end

  def edit
  end

  def update
    GearType.update(@gear_type.id, gear_params)
    redirect_to(gear_types_path)
  end

  def destroy
    @gear_type.destroy
    redirect_to request.referer
  end

  private
  
  def find_gear_type
    @gear_type = GearType.find(params[:id])
  end

  def gear_type_params
    params.required(:gear_type).permit(:name)
  end

end

app/views/gear_types/_form.html.slim
= simple_form_for(@gear_type) do |f|
  = f.error_notification
  = f.input :name
  = f.button :submit, 'Save'

app/views/gear_types/edit.html.slim
#header_container
  h2
    | Edit Gear Type
= render 'form'

app/views/gear_types/index.html.slim
#header_container
  h2
    | Gear Types
#content
  - @gear_types.each do |gt|
    h2
      = gt.name
    ul
      li.widget.mini
        = link_to icon("fa fa-times"), gear_type_path(gt), method: :delete
      li.widget.mini
        = link_to icon("fa fa-pencil"), edit_gear_type_path(gt)

app/views/gear_types/new.html.slim
#header_container
  h2
    | New Gear Type
= render 'form'