config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/donate', path: :donate
  get 'static_pages/settings', path: :settings

  get 'static_pages/home', path: :home

  get 'search' => 'application#search', as: :search

   root 'static_pages#home'

  resources :climbers
  resources :posts
  resources :gears
  resources :gear_types
  resources :loans
  resources :events do
    member do
      get 'signup'
      get 'signdown'
    end
  end

  resources :app_configs, only: [:update]
  get '/app_configs' => 'app_configs#edit', as: :edit_app_configs
  resources :pending_climbers, only: [:new, :create, :index, :destroy]
  resources :faqs, except: [:show]

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :climbers
  has_many :photos

  accepts_nested_attributes_for :photos, reject_if: :all_blank, allow_destroy: true

  has_attached_file :cover, styles: {splash: '960x960', thumb: '256x256'}, default_url: ActionController::Base.helpers.asset_path('missing_event.jpg')


  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/
  validates :name, :start_date, :end_date, presence: true

  def nonmembers
    return [] if self.emails.blank?
    return self.emails.split(',').count
  end

  def num_signed_up
    self.climbers.count + self.nonmembers.count
  end


  def self.view user
    if user.nil? || user.id.nil?
      Event.where('private = false')
    else
      Event.all
    end
  end

  def add_email email
    if self.emails.blank?
      self.emails = email
    else
      self.emails = self.emails + "," + email.to_s
    end
    return self.save
  end

  def get_range
    # Return human readable string of the event time
    start_date = self.start_date.to_date.to_s(:short)
    end_date = self.end_date.to_date.to_s(:short)
    start_time = Time.at(self.start_date).strftime('%R')
    end_time = Time.at(self.end_date).strftime('%R')
    if start_date == end_date
      # the event is a single day event
      return "#{start_date} #{start_time} - #{end_time}" if start_time != end_time
      return "#{start_date}"
    else
      # the event spans multiple days
      return "#{start_date} - #{end_date}"
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action CASClient::Frameworks::Rails::Filter, only: [:new, :edit, :create, :update, :destroy, :signup, :signdown]
  before_action :set_event, only: [:show, :edit, :update, :destroy, :signup, :signdown]
  layout 'show', only: :show

  # GET /events
  def index
    @events = Event.all.order('start_date DESC');
    @new = new_event_path(@event) if can? :create, Event
  end

  # GET /events/1
  def show
    @index = events_path
    @edit = edit_event_path(@event) if can? :edit, @event
    @new = new_event_path(@event) if can? :create, Event
    @delete = @event if can? :destroy, Event
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def signup
    if current_user.nil? || current_user.id.nil?
      @event.add_email(params[:email])
      # guest user
    else
      # reg user
      @event.climbers << current_user
      @event.save
    end
    flash[:notice] = 'Signed up!'

    redirect_to @event
  end

  def signdown
    @event.climbers.delete(current_user)
    flash[:notice] = "Signed down!"
    redirect_to @event
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.required(:event).permit(:name, :description, :start_date, :end_date, :signup, :cover, :private, :public_signup, :photos, photos_attributes: [:id, :image, :image_file_name, :image_content_type, :image_file_size, :event_id, :_destroy])
    end
end

app/views/events/_event_card.html.slim
= content_tag :div, class: 'card event_card', style: "background-image: url('#{event_card.cover(:thumb)}')"
  .heading_container
    a href = event_path(event_card)
      h2.slide_heading
        = event_card.name
      h4.slide_subheading
        = event_card.start_date.to_date.to_s(:long)

app/views/events/_form.html.slim
= simple_form_for(@event) do |f|
  = f.error_notification
  = f.input :name
  = f.input :description
  = f.input :start_date
  = f.input :end_date
  = f.label 'Cover Photo'
  = f.file_field :cover


  
  = f.label 'Sign Ups'
  = f.check_box :signup
  = f.hint "(Allow logged in users to sign up for this event)"

  = f.label 'Public Sign Ups'
  = f.check_box :public_signup
  = f.hint "(Allow non-members to sign up for this event)"

  = f.label 'Private'
  = f.check_box :private
  = f.hint "(Hide this event from non-logged in users)"

  #photos
    = f.simple_fields_for :photos do |photo|
      = render 'photo_fields', f: photo
    .links
      = link_to_add_association 'Add Photo', f, :photos

  = f.button :submit, 'Save Event'

app/views/events/_photo_fields.html.slim
.nested-fields
  = f.file_field :image
  = link_to_remove_association "remove photo", f

app/views/events/edit.html.slim
#header_container
  h2
    = @event.name
= render 'form'

app/views/events/index.html.slim
#header_container
  h2
    = @appconfig.events_header

.tiles
  - if @events.empty?
    #content
      p
        | No events found!
  - else
    = render partial: 'event_card', collection: @events

app/views/events/new.html.slim
#header_container
  h2
    | New event
= render 'form'

app/views/events/show.html.slim
= content_tag :div, id: "header_container", class: 'bg', style: "background-image: url('#{@event.cover(:splash)}')"
  h2
    = @event.name
  h6
    = @event.get_range
  - if can? :signup, @event
    =  form_tag signup_event_path(@event), method: 'get' do
      - # setting the form to use get is a hack to allow
      - # requests to pass through the rubycas gateway filter
      - # which for some reason converts all requests to get
      - # for non logged in users
      - if current_user.nil? || current_user.id.nil?
        = text_field_tag :email,"", class: 'signup_field', placeholder: 'Enter your email!'
      = submit_tag "Signup", id:'signup'
  - elsif member? && current_user.signedup?(@event)
      = form_tag signdown_event_path(@event), method: 'get' do
        = submit_tag "Signed Up", id: 'signup', title: 'Click to un-sign-up'
  .maskw
.tiles#event_show_tiles
  = render partial: 'photos/photo_card', collection: @event.photos
#content
  p
    = @event.description
  - if @event.signup
    h2
      = "#{@event.num_signed_up} signed up"