config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/donate', path: :donate
  get 'static_pages/settings', path: :settings

  get 'static_pages/home', path: :home

  get 'search' => 'application#search', as: :search

   root 'static_pages#home'

  resources :climbers
  resources :posts
  resources :gears
  resources :gear_types
  resources :loans
  resources :events do
    member do
      get 'signup'
      get 'signdown'
    end
  end

  resources :app_configs, only: [:update]
  get '/app_configs' => 'app_configs#edit', as: :edit_app_configs
  resources :pending_climbers, only: [:new, :create, :index, :destroy]
  resources :faqs, except: [:show]

end

app/models/gear.rb
class Gear < ActiveRecord::Base
  belongs_to :gear_type
  belongs_to :climber

  validates :climber, :gear_type_id, :quantity, :name, presence: true
  validates :quantity, numericality: { only_integer: true, greater_than: 0 }
end

app/models/gear_type.rb
class GearType < ActiveRecord::Base
  has_many :gears
  validates :name, presence: true
end

app/controllers/gear_controller.rb
class GearController < ApplicationController
  
  before_action :find_gear, only: [:edit, :destroy, :update]

  def new
  end

  def create
    p = gear_params
    p[:climber_id] = current_user.id
    @gear = Gear.create(p)
    redirect_to(@gear)
  end

  def edit
  end

  def update
    Gear.update(@gear.id, gear_params)
    redirect_to(@gear)
  end

  def destroy
    @gear.destroy
    redirect_to action: 'index'
  end

  private
  
  def find_gear
    @gear = Gear.find(params[:id])
  end

  def gear_params
    params.required(:gear).permit(:description, :quantity)
  end

end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  before_action CASClient::Frameworks::Rails::Filter, only: [:new, :edit, :create, :update, :destroy]
  before_action :find_gear, only: [:edit, :destroy, :update]

  def new
    @gear = Gear.new
  end

  def create
    p = gear_params
    p[:climber_id] ||= current_user.id
    # check if climber already has this type of gear
    #gear = current_user.gears
    # gear.each do |g| 
    #  if g.gear_type_id == p[:gear_type_id].to_i
    #    g.quantity += p[:quantity].to_i
    #    if g.description.nil?
    #      g.description = p[:description]
    #    elsif p[:description].present?
    #      g.description += p[:description]
    #    end
    #    @gear = g
    #    break
    #  end
    # end
    @gear ||= Gear.new(p)
    if @gear.save
      redirect_to(current_user, notice: 'Gear successfully updated')
    else
      render :new
    end
  end

  def edit
  end

  def update
    Gear.update(@gear.id, gear_params)
    redirect_to(@gear)
  end

  def destroy
    @gear.destroy
    redirect_to request.referer
  end

  private
  
  def find_gear
    @gear = Gear.find(params[:id])
  end

  def gear_params
    params.required(:gear).permit(:name, :description, :quantity, :gear_type_id, :climber_id)
  end

end

app/views/gears/_form.html.slim
= simple_form_for(@gear) do |f|
  = f.error_notification
  = f.input :name
  = f.input :gear_type_id, collection: GearType.all
  = f.input :description
  = f.input :quantity
  = f.input :climber_id, collection: Climber.all if current_user.role == 'admin'
  = f.button :submit, 'Save'

app/views/gears/_gear_item.html.slim
.gear_item
  h2
    = "#{gear_item.name} x#{gear_item.quantity}"
  h3.subtitle
    = gear_item.gear_type.name
  p
    = gear_item.description
  - if can? :manage, gear_item
    ul
      li.widget.mini
        = link_to icon("fa fa-times"), gear_path(gear_item), method: :delete
      li.widget.mini
        = link_to icon("fa fa-pencil"), edit_gear_path(gear_item)

app/views/gears/edit.html.slim
#header_container
  h2
    | Edit Gear!
= render 'form'

app/views/gears/new.html.slim
#header_container
  h2
    | New Gear!
= render 'form'